# Generated by Django 6.0.2 on 2026-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_review_unique_together_review_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True, help_text='Manually control if product is shown as in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Manually mark as new arrival'),
        ),
    ]
