# Generated by Django 6.0.2 on 2026-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_in_stock_product_is_new_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Review must be approved to be visible'),
        ),
    ]
