services:
  # Web Service
  - type: web
    name: sportstore
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn sportstore.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  # PostgreSQL Database
  - name: sportstore-db
    databaseName: sportstore
    user: sportstore
